sudo: false
language: python
cache: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - python setup.py -q install
script: nosetests --with-coverage --cover-package=squidsleuth

# Coverage metrics
before_install:
  - pip install codecov
after_success:
  - codecov
